### ISSUE TITLE
Skip data/ when copying examples?

### ISSUE THREAD

**Issue by jbednar** [pyviz/pyct#28] opened 2018-05-18 14:42 UTC
> I tried to build datashader's docs, but my disk ran out of room when copying the examples.  Turns out that it was copying all of the contents of examples/, which in my case included hundreds of gigabytes of data (some of which is needed to build the docs):

```
def examples(path='datashader-examples', verbose=False, force=False, root=__file__):
    """
    Copies the notebooks to the supplied path.
    """
    filepath = os.path.abspath(os.path.dirname(root))
    example_dir = os.path.join(filepath, './examples')
    if not os.path.exists(example_dir):
        example_dir = os.path.join(filepath, '../examples')
    if os.path.exists(path):
        if not force:
            print('%s directory already exists, either delete it or set the force flag' % path)
            return
        shutil.rmtree(path)
    ignore = shutil.ignore_patterns('.ipynb_checkpoints', '*.pyc', '*~')
    tree_root = os.path.abspath(example_dir)
    if os.path.isdir(tree_root):
        shutil.copytree(tree_root, path, ignore=ignore, symlinks=True)
    else:
        print('Cannot find %s' % tree_root)



def package_assets(example_path):
    """
    Generates pseudo-packages for the examples directory.
    """
    examples(example_path, force=True, root=__file__)
    for root, dirs, files in os.walk(example_path):
        walker(root, dirs+files)
    setup_args['packages'] += packages
    for p, exts in extensions.items():
        if exts:
            setup_args['package_data'][p] = exts
```

For now, I turned `data/` into a symlink, but it seems like we should only be packaging up files that are actually in git, and not gratuitously copying the entire filesystem?

**Comment by ceball** [comment] 2018-05-18 17:28
See also #22 (this issue could probably be a comment there).

**Comment by ceball** [comment] 2018-05-20 03:56
This is a duplicate of https://github.com/pyviz/pyct/issues/22 (needlessly copying examples/ then deleting the copy during pip develop install).

**Closed** 2018-05-20 03:56 UTC
